benchmarks/lasso/solvers/baseline.py

I am doing something wrong since use_acceleration is never set to True:
```
(base) ➜  benchOpt git:(add_fista) ✗ benchopt run lasso -s baseline -n 1 -d boston
Boston
|--Lasso regression(reg=0.05)
|----Baseline(use_acceleration=false): done               
|----Baseline(use_acceleration=false): done               
|--Lasso regression(reg=0.1)
|----Baseline(use_acceleration=false): done               
|----Baseline(use_acceleration=false): done               
|--Lasso regression(reg=0.5)
|----Baseline(use_acceleration=false): done               
|----Baseline(use_acceleration=false): done    
```
We can also discuss the naming, I would go for `w` instead of  `z_hat`
(same as in sklearn),  and I'm not very satisfied with `use_acceleration` either

ENH add FISTA solver for Lasso benchmark

---

benchmarks/lasso/solvers/baseline.py
doc/how.rst

-  added a comment to mention that parameters defined in `parameters` can be accessed without being set in an init.
-  replaced z by w
- avoided computation of X.T @ X for Lipschitz constant (costly)

CLN update Lasso:Baseline solver for a better doc

---

README.md

Simple fix, otherwise you get:
```
$ pip install https://github.com/benchopt/benchopt                                                                               ~
Collecting https://github.com/benchopt/benchopt
Downloading https://github.com/benchopt/benchopt
- 105 kB 1.4 MB/s
ERROR: Cannot unpack file /tmp/pip-unpack-75wvkp8v/benchopt (downloaded from /tmp/pip-req-build-9m5j3we2, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-9m5j3we2
```

FIX install link in README.md

---

benchmarks/logreg/solvers/liblinear.py
benchopt/base.py
benchopt/config.py
benchopt/runner.py
benchopt/util.py
conftest.py

Solves #27
Instead of not raising an error in `pip_install_in_env` when `PRINT_INSTALL_ERROR=False`, now the error is always raised, but caught in `DependenciesMixin.install`.
In a second part of this PR, in ` benchopt/runner.py`, it prevents the solver from running if the module caught an ImportError in `safe_import`.

ENH Add install and import failure message

---

benchmarks/lasso/solvers/statsmodels.py

I have added a comparison with `statsmodels` (now having lasso, enet, etc.) for versions 0.11.1
Results are in favor of `sklearn`.

ENH add statsmodels solver for lasso

---

benchmarks/nnls/solvers/nnls_scipy.py

Uses https://github.com/benchopt/benchOpt/issues/31#issuecomment-684972791 to capture stdout in scipy FORTRAN solver.
Before:
```
Simulated[n_samples=100,n_features=10000]
|--Non negative least squares[fit_intercept=false]
|----Baseline[use_acceleration=false]: done               
|----Baseline[use_acceleration=true]: done                
|----Cd: done                                             
|----Scipy:   0.0% (0 / 5)
NNLS quitting on iteration count.
|----Scipy:   0.0% (1 / 5)
NNLS quitting on iteration count.
|----Scipy:   0.0% (2 / 5)
NNLS quitting on iteration count.
|----Scipy:   0.0% (3 / 5)
NNLS quitting on iteration count.
|----Scipy:   0.0% (4 / 5)
NNLS quitting on iteration count.
|----Scipy:   1.0% (0 / 5)
NNLS quitting on iteration count.
|----Scipy:   1.0% (1 / 5)
NNLS …
```

Capture stdout in scipy FORTRAN solver

---

benchopt/util.py

The parametrized solver and datasets are checked and installed multiple times.
This PR fixes this.

FIX install parametrized class only once

---

benchopt/base.py
benchopt/cli.py
benchopt/runner.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/julia_pgd.py
benchopt/tests/test_cli.py
benchopt/utils/julia_helpers.py
benchopt/utils/misc.py
benchopt/utils/shell_cmd.py
continuous_integration/install.sh

Add pre/post install hook and use them to make sure julia is correctly installed.
This is to avoid having to clone manually `.julia/registries/General` in every repo, as the failures in benchopt/benchmark_logreg_l2#1 .
This requires changing a bit the API for Julia solver as it should now derive from `JuliaSolver` and the proper preamble is now:
```python
from benchopt.utils.julia_helpers import JuliaSolver
from benchopt.utils.julia_helpers import get_jl_interpreter
from benchopt.utils.julia_helpers import assert_julia_installed
with safe_import_context() as import_ctx:
assert_julia_installed()
```

ENH install hook / JuliaSover / FIX cache

---

CHANGE.md
MANIFEST.in
benchopt/__init__.py
benchopt/cli.py
benchopt/utils/shell_cmd.py
setup.py

If the version of benchopt in a conda env is different from the one in the main process, raise a warning.
TODO:

ENH raise a warning when unmatched benchopt versions

---

benchopt/cli.py
benchopt/runner.py
benchopt/utils/colorify.py
benchopt/utils/pdb_helpers.py

add a `--pdb` option to the `run` command so a debugger (`ipdb` if present else `pdb`) is open on error for the solver.
This should prove helpful to develop new solvers.

ENH add option to launch a debugger on error

---

benchopt/benchmark.py
benchopt/cli.py
benchopt/config.py
benchopt/runner.py
benchopt/tests/conftest.py
benchopt/utils/files.py
benchopt/utils/github.py
benchopt/utils/pdb_helpers.py
benchopt/viz/__init__.py
examples/plot_run_benchmark.py
examples/plot_run_benchmark_python_R_julia.py
setup.py

Add a `benchopt publish` command to upload the benchmark results to [`benchopt/results`](https://github.com/benchopt/results).
The command is based on `pygithub` and upload the file when given a token. The token can be set either directly with `-t TOKEN`, with an environment variable `BENCHO_GITHUB_TOKEN` or in the config file.

ENH add benchopt publish command

---

CHANGE.md
README.rst
benchopt/cli.py
benchopt/tests/test_cli.py
doc/index.rst

- Update the doc to call `benchopt run --env` for the first benchmarks (no install required).
- Make the `--env-name` option working.

FIX clean up some left-over from setting --local as default

---

benchopt/runner.py

The install errors are not properly catched and displayed.
This PR fix this for datasets and solvers.
This gives output like:

FIX improve install errors output

---

benchopt/benchmark.py
benchopt/cli.py
benchopt/cli/__init__.py
benchopt/cli/helpers.py
benchopt/cli/main.py
benchopt/cli/process_results.py
benchopt/config.py
benchopt/runner.py
benchopt/tests/test_cli.py
benchopt/tests/test_config.py
benchopt/tests/test_runner.py
benchopt/utils/files.py
benchopt/utils/pdb_helpers.py
benchopt/utils/shell_cmd.py
doc/cli.rst
doc/conf.py
doc/config.rst
doc/doc-requirements.txt
doc/how.rst
doc/index.rst
doc/publish.rst
doc/sphinxext/sphinx_click_semantic_group.py
doc/whats_new.rst
setup.py

Enh clean config

---

benchopt/plotting/helpers_compat.py
benchopt/plotting/plot_histogram.py

Make barplots with plotly for results (now all the plots will render nicely).
Below see how it renders. To the left is the old behavior (still accessible when `plotly=False`: this is not a capture of the website but a capture of the "make" page with `plotly=False`, it is exactly as before even with the changes made to adapt with plotly). To the right is with `plotly=True`.

Plotly barplot

---

benchopt/cli/main.py

When click autocompletion is activated, `benchopt run` suggests the list of sub-directories in current directory for the BENCHMARK argument.

Enable autocompletion for BENCHMARK argument

---

README.rst
doc/index.rst

Temporary update of installation instruction:
```
$ git clone https://github.com/benchopt/benchOpt
$ pip install -e benchOpt
```
to replace `pip install benchopt` while PyPI version is 1.0.0 and thus not compatible with current version of the doc (c.f. #130)

temporary install instruction while PyPI version is not up-to-date

---

benchopt/cli/main.py
benchopt/utils/sys_info.py

tests in benchopt/benchmark_lasso#20 fail because when importing a test, `pytest` modify the `sys.path` by pre-pending the root in it. This can cause failure in case the calling `benchopt` is installed in `python3.8` and the conda env where the test are run is with `python3.9`, as the packages are imported from the wrong site-package.
This PR make use of the `--import-mode importlib` option from `pytest` which does not modify the python path, as described here: https://docs.pytest.org/en/stable/pythonpath.html

DBG fail in benchopt test due to sys.path modification

---

benchopt/benchmark.py
benchopt/tests/__init__.py
benchopt/tests/conftest.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_benchmarks/dummy_benchmark/xfail.py

Add an API to allow `xfailing` specific solver in benchmark tests easily.
One should add a file `xfail.py` with a function `xfail_test_name` and use the fixeture `xfail_check` to be able to call this function in the test. See `test_benchmakr.py::test_solver_install` for instance.

ENH add xfail config file for benchmark test

---

benchopt/plotting/helpers_compat.py

Now the overs show the whole name of the solver (better when different solvers with the same prefix showing)I
And for the quantiles traces, it removes the "trace .." on the right side of the hover box.

[ENH]  better hovers with plotly

---

benchopt/runner.py
benchopt/stopping_criterion.py
benchopt/tests/test_benchmarks.py
doc/whats_new.rst

This is a concurrent solution for #149.
I propose to refactor the code for the stopping criterion with 2 parts:
- One which check global stuff like `timeout`, `max_runs` and make sure we stop when we diverged.
- One which is for now fixed but should be made objective specific: the actual stopping criterion.
For now, I implemented the `SufficientDescentCriterion`, which check the same as what we were checking before.
But we could add other easily and make the choice depend on the `objective`.

ENH add stopping criterion

---

benchopt/config.py
benchopt/utils/conda_env_cmd.py
doc/whats_new.rst

The rational of allow install was to avoid silently installing stuff on `benchopt run`.
Now that per #135, `install` and `run` are spearated, the user knows that he is doing an install so the allow install is not really relevant anymore.
this PR supress it as it might be confusing.

CLN remove allow_install

---

benchopt/plotting/generate_html.py
benchopt/plotting/html/static/hover_index.css
benchopt/plotting/html/static/main.css
benchopt/plotting/html/templates/benchmark.mako.html
benchopt/plotting/html/templates/index.mako.html
benchopt/plotting/html/templates/result.mako.html

This PR modifies for the results page:
- the index is in a grid
- the table contains main and subsidiary system informations (main=cpu/ram/cuda, sub=plateform/num_threads/processor) and displays them if available
- we can filter the table from the main informations (for when there will be a lot of files)
- informations + scipy/numpy versions appear if needed above plots that are up to date with modifications from PR that didn't make the cut to the main repo in the transfer.
- Responsive to different screen sizes + ok chrome / firefox
See the video attached to tell me where modifications are needed :slightly_smiling_face: 
https://user-images.githubusercontent.com/57089823/117458298-6dd44280-af4a-11eb-926f-792e8a72fcfc.mp4

Update results page

---

benchopt/plotting/html/static/main.css
benchopt/plotting/html/templates/benchmark.mako.html

Observed issues:
Navigation bar issue seem fixable using percentages (need more testing for now cross platform).

[WIP] Fixes for results page

---

benchopt/plotting/html/static/main.css
benchopt/plotting/html/templates/benchmark.mako.html
benchopt/plotting/html/templates/index.mako.html
benchopt/plotting/html/templates/result.mako.html

#164 wasn't finished because only worked for computers.
Now the sidebar (which isn't handled well on small screens) is replaced by a top bar (to be styled better later on but at least everything is visible for now this way)
PS1: I did the modifications on the dataset names too for the options, see images below showing the mobile behavior
PS2: working on the index issue after that (but can't reproduce the issue for now on devices other than from the fruit company...)
Datasets options modif |  on large screens sidebar | on smaller screens topbar
:-------------------------:|:-------------------------:|:------------------------------:

[MRG OK] Mobile support sidebar (see #164)

---

benchopt/plotting/html/static/hover_index.css
benchopt/plotting/html/templates/benchmark.mako.html

This was from a typo that had no influence on other device... See the simulation below (the opened inspect element is to show that only one small line needed modifications)
Before on an iPad | after 
:--------------------: | :-------------------------:

Fix ios index

---

benchopt/plotting/html/static/main.css
benchopt/plotting/html/templates/benchmark.mako.html

A menu-type filter for mobiles that can replace the temporary fix-style.
The sidebar for non-mobile is not changed.
Before             |  After
:-------------------------:|:-------------------------:

Style mobile sidebar

---

.github/workflows/test.yml
benchopt/benchmark.py
benchopt/tests/conftest.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_benchmarks/dummy_benchmark/test_config.py
benchopt/utils/conda_env_cmd.py
benchopt/utils/shell_cmd.py

Try to fix instabilities in package install due to having both `defaults` and `conda-forge` by only using `conda-forge`.
Also propagate the changes from #145 as it requires a bit rebase on is related to this.

FIX instabilities in R/Julia install

---

benchopt/plotting/html/static/hover_index.css
benchopt/plotting/html/static/main.css
benchopt/plotting/plot_objective_curve.py

- Add an option to toggle between semilogy plots and loglog with plotly (cc @mathurinm). It presents iself as a dropdown menu and the active element is showed. Default is loglog (current plots). (Of course after clicking it shrinks back to a normal menu, the image below is to show how options are displayed)
- Comments in CSS added for clarity.

Scales plotly option

---

benchopt/benchmark.py
benchopt/tests/__init__.py
benchopt/tests/test_cli.py
examples/plot_run_benchmark_python_R_julia.py

cf #178 
I think we could even change it to "^{p} {opening bracket or end of string}.*"   
at least with this change `-s celer` does not trigger `pgd[use_acceleration=False]"
WDYT @tomMoral ?

FIX pattern should *start* with solver or dataset name

---

benchopt/plotting/helpers_compat.py
benchopt/plotting/plot_objective_curve.py

1) I changed the default scale to semilogy in plotly. I find loglog very confusing, as it exaggerates the importance of early iterations ; it also does not reflect how crushingly superior an algorithm can be.
2) I increased the marker scales, as I found them hard to read (given that the colors are already quite similar)
Before marker size change (notice how the two red curves are hard to distinguish):
After:

larger markers, use semilogy scale by default

---

benchopt/utils/misc.py

The test are broken on `master` due to an update in `pip`.
It seems that now, distribution do not have a `editable` attribute but rely on `dist_is_editable` to check if it is editable.
This PR should make this more robust.

FIX editable distribution in pip

---

.circleci/config.yml
benchopt/cli/__init__.py
benchopt/helpers/julia.py
benchopt/utils/conda_env_cmd.py
benchopt/utils/misc.py

The failure in benchmark_lasso seems to be linked to a bad fix in #195 that does not work with `benchopt` install in non-dev mode.
This should fix this and also fix bad behavior when installing `benchopt` in dev mode with new commits.

FIX benchopt install in env

---

.circleci/config.yml
pyproject.toml

Circle CI doc build fails. 
It would seem that the support for the parameter `use_2to3` was dropped in the last version (58.0) of setuptools (as it was deprecated for some time now). But sphinx-bootstrap uses it.
Setuptools developers are working on some fixes since the release, but in the mean time maybe we should pin the version to build the doc.

Fix doc CI

---

.circleci/config.yml
pyproject.toml

Now that sphinx-bootstrap-theme has released the version 0.8.0 we should no longer need to pin setuptools version.
(pending that other packages don't use the `use_2to3` parameter).

Reverse setuptools version

---

benchopt/plotting/plot_objective_curve.py

The reason why the `logreg_l2` plots were "weird looking" was that there was a point that took a very long time to be computed that had for value `inf`: so not visible.
By removing the `inf` values in the plots, axis scales are much more relevant (see before/after)
| Before | After  |
|---|---|
| ![With inf values](https://user-images.githubusercontent.com/57089823/133259489-f1a98f59-01b1-43f1-bf59-3b8dcfd70395.png)|![Without inf values](https://user-images.githubusercontent.com/57089823/133259628-0ba8a4a9-2360-44bd-ac0e-1adce8703f70.png)|

Remove inf values from plotting

---

benchopt/tests/test_benchmarks/dummy_benchmark/solvers/sklearn.py

try to fix failures from https://github.com/benchopt/benchOpt/runs/3718219572?check_suite_focus=true
If this works, we will try to reproduce the segfault for `sklearn` in a separate PR.

FIX use conda install for sklearn

---

setup.cfg

We use  `fig.add_hline` in helpers_compat.py ; it was added in plotly 4.12 so I made it a requirement. @qb3 had an issue otherwise.
See https://stackoverflow.com/questions/68296479/why-am-i-getting-plotly-express-attribute-error-attributeerror-figure-objec

Add minimal plotly version

---

benchopt/plotting/helpers_compat.py

Colors in plotly need to be RGBa to match with matplotlib (*255).
(Fixes #213 @mathurinm)

Plolty colors match matplotlib

---

.circleci/config.yml
benchopt/plotting/html/templates/result.mako.html
pyproject.toml

- Display options for BenchOpt results a little more organized (poke @mathurinm)
- `setuptools` released the version 58.5.0 that broke the CI (and a lot of others like scipy's), like last time until they fix the problem we can pin the version.

Display options with newline and temporary ci fix setuptools 

---

doc/index.rst

Correcting same math typo as in the Huber example, for nice display in the doc.
Could be interesting (if the number of benchmarks objective become large) to have an automated way to go from the benchmarks to the docs...
but I have no idea if this is possible.

Math style correction in doc

---

doc/index.rst
examples/plot_run_benchmark.py

The first figure that users see when they land on the doc page is a bit "heavy" in my opinion, so I removed some solvers, and use a suboptimality plot:
Before:
After (on my computer, I'll wait to see the results on CI):

DOC: use less solvers, use suboptimality

---

benchopt/runner.py
benchopt/stopping_criterion.py
benchopt/utils/colorify.py
benchopt/utils/pdb_helpers.py

Try to fix the length of the output.
What is missing is actually try to reduce the size of the name of the solver if the console is too small.
An idea would be to `truncate` the parameters with ellipsis: `|---solver[p=1,...] xx% (X / X reps)`

CLN fix print length

---

benchopt/cli/process_results.py
benchopt/runner.py
benchopt/utils/dependencies_mixin.py
doc/conf.py
doc/config.rst
doc/how.rst
doc/index.rst
doc/publish.rst
doc/sphinxext/gh_substitutions.py
doc/whats_new.rst

closes #249 
I have used `Benchopt` when it's at the start of a sentence, and `benchopt` otherwise

Rename BenchOpt to Benchopt

---

.circleci/config.yml
benchopt/plotting/html/static/benchmark.js
benchopt/plotting/html/templates/benchmark.mako.html

As discussed to resolve #229, for local rendering only, this adds a select box at the left of the bench result's name (or just below depending on the available space) and a trash icon below the table.
If selected, then the trash icon displays the path of several files that are inside the `outputs` folder:
- the selected `.csv` datasets,
- the selected `.html` associated generated pages,
- the cached json file (so the next time we call `benchopt plot --all .` for example the deleted benchs are not presented in the results table).
Then, one can simply click on `copy to clipboard` and paste the command in the terminal from the `outputs` folder.
For the current time, there is also a `hide row` button that will hide the selected rows (until the page is refreshed as it is static) but it can be …

Alternative to remove local file 

---

benchopt/cli/helpers.py
benchopt/cli/main.py
benchopt/cli/process_results.py
benchopt/utils/conda_env_cmd.py
pyproject.toml
setup.cfg

Deprecations reported in #182 :

FIX deprecation warnings in test_cli

---

benchopt/base.py
benchopt/benchmark.py
benchopt/utils/dynamic_modules.py
benchopt/utils/safe_import.py
doc/advanced.rst
doc/index.rst
doc/whats_new.rst

This PR adds a method in the `import_ctx` to be able to dynamically load modules from the `utils` subfolder of the benchmark.
The idea is to be able to call the method `import_from` of `import_ctx`, which handles the import in a dynamic way.
```python
from benchopt import safe_import_context
with safe_import_context() as import_ctx:
alpha_max = import_ctx.import_from('alpha_max')  # Import a module
get_alpha_max = import_ctx.import_from(  # Import  a func from a module
'alpha_max', 'get_alpha_max'
)
```
Here, the file `alpha_max.py` with a function `get_alpha_max` should be available in the `BENCHMARK_DIR/utils` folder.
Fixes #279

ENH add safe_import_context.import_from to import from benchmark/utils

---

benchopt/cli/main.py
benchopt/tests/test_cli.py
doc/whats_new.rst

fixes #225 
I have an issue, the warnings are captured even with BENCHOPT_DEBUG=1, I think they should not because the user won't be notified of the deprecation.
It remains to adapt the test if you agree with this @tomMoral @agramfort

API deprecate -p shortcut in favor of -o for Objective

---

benchopt/base.py

Raise Future and not Deprecation warning in the `base.py` file (cf @mathurinm  #281)

Raise FutureWarning instead of DeprecationWarning if stop_strategy is used

---

benchopt/base.py

We encountered an issue with hashing/pickling a user defined `Objective` where an attribute `dataset` was created in `set_data`.
This was due to the fact that it overrided the original dataset object.
To avoid this, moving to a private attribute, as it is done for other classes such as `Solver._objective`.

FIX private attr to store dataset in objective

---

.circleci/config.yml

We got a warning on circle
Fix from:
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

update legacy docker image in circle

---

benchopt/base.py
benchopt/tests/test_benchmarks.py

For some benchmark, the return of the solver is not a simple `np.array` but a complex object.
For those, the test are too restrictive. I propose to skip part of the test when the dataset return `dimension = 'object'`.
Also, some algorithms do not converge quickly. thus `test_solver` can be very long/slow.
I will try to mitigate this in the PR.

TST make test more permissive for complex benchmarks

---

benchopt/cli/helpers.py
setup.cfg

`click` 8.1.0 is out today, and they dropped the `autocompletion` parameter support in favor of the `shell_complete` one.
cf [their changelog](https://click.palletsprojects.com/en/8.1.x/changes/)

click 8.1 update autocomplete

---

examples/plot_run_benchmark.py

https://github.com/benchopt/benchmark_logreg_l2/pull/27 removed this parameter from the benchmark, which broke the doc.
This is a fix

DOC rm fit_intercept in logreg L2 example

---

benchopt/runner.py

It's hard to distinguish when we're moving to another dataset:
This PR indents the solver names by 2 spaces for easier visualization of the separation:

ENH indent CLI output

---

benchopt/config.py
benchopt/constants.py
benchopt/plotting/__init__.py
benchopt/plotting/generate_html.py
benchopt/plotting/plot_bar_chart.py
doc/config.rst

What's currently referred to as histograms in the result plots are actually bar charts (or bar plots). This pull request replaces "histogram" with "bar chart" everywhere.

FIX rename histogram as bar chart

---

.gitignore

I believe that the ignore patterns in the `.gitignore` should be prefaced with slashes (so that they only refer to folders in the root directory). Otherwise they also ignore, for instance, `benchopt/plotting/html`, which I don't think is intended (particularly not since all the files in that folder are actually being tracked).

FIX preface root folder ignores with slashes

---

benchopt/tests/test_benchmarks.py

This has the unwanted side effect of potentially skipping some solvers depending on the simulated dataset configuration.
I will propose a follow-up PR to fix this.

BUG In solver test switched `set_objective` to `_set_objective` to ensure skipping happens

---

benchopt/helpers/julia.py
doc/how.rst

This allows to easily install julia dependencies from a github repo, using:
```python
class Solver(JuliaSolver):
julia_requirements = ["pkg_name::https://url.to/package#branch"]
```
tested for the following benchmark: benchopt/benchmark_logreg_l2#29

ENH improve install of julia deps

---

benchopt/utils/sys_info.py

Fixes #378 and Fixes #163 by collection GPU name and cuda version
This doesn't use `pynvml` (which is "a wrapper around NVML library" that does, more quickly, what the smi thinner wrapper `nvidia-smi -q -x` does)

Get cuda info without nvcc

---

benchopt/utils/sys_info.py

Fixes #395 with a first try/except on `nvidia-smi` command check output.

[FIX] Safe exit cuda

---

benchopt/benchmark.py
benchopt/tests/test_runner.py

Support "solver[parameter=1e-5]" in CLI. (follow-up of #362).

Support exp notation in CLI parameters

---

benchopt/benchmark.py
benchopt/cli/completion.py
benchopt/cli/helpers.py
benchopt/cli/main.py
benchopt/cli/process_results.py
benchopt/plotting/__init__.py
benchopt/plotting/generate_html.py
benchopt/plotting/html/static/benchmark.js
benchopt/plotting/html/templates/benchmark.mako.html
benchopt/runner.py
benchopt/tests/__init__.py
benchopt/tests/test_cli.py
doc/whats_new.rst
setup.cfg

Parquet files are smaller than CSV files. So we change the CSV output by a Parquet file output.
Compatibility with previous CSV files is kept.
There is a new cli command to convert Parquet files to CSV file (or html or json) : 
`$ benchopt convert [parquet_file] --to [requested_format]`
TODO:

Compress data

---

benchopt/stopping_criterion.py

This should fix the issue from benchopt/benchmark_jointdiag#4.
The issue is that we rescale the delta by `loss[0]` so for negative losses this reverses the dynamic. I added some absolute value to avoid this.
Let me know if this fixes the issue.

FIX non-diverging negative losses

---

benchopt/tests/test_benchmarks.py

In the NMF benchmark beta is a list of two arrays of different shapes, so the current test code fails
https://github.com/cohenjer/benchmark-nmf/blob/main/solvers/apg.py#L33
https://github.com/cohenjer/benchmark-nmf/blob/main/solvers/apg.py#L59
https://github.com/cohenjer/benchmark-nmf/runs/7410359135?check_suite_focus=true#step:6:451
@cohenjer

fix for objective and solvers returning list of arrays

---

benchopt/utils/dynamic_modules.py

The import error for files in a benchmark `utils` were not displayed, which leaded to cryptic errors:
This PR makes it much clearer:
closes #436

FIX import error in utils displayed

---

benchopt/cli/helpers.py

Closes #336 @zaccharieramzi could you delete `.config/benchopt.ini`, call `benchopt config set conda_cmd mamba` and see if the file has the proper mode now?

FIX create config file with mode 600 in cli set()

---

benchopt/stopping_criterion.py

Following the merge of #461, a print used for debugging slipped through to the code base.
Example of logs that one gets when running a benchmark
```shell
Simulated[a=2,b=-5]                                                                                                                                                                                   
|--Affine[with_exp=True]                                                                                                                                                                            
1.484131591025766e+102piness=very-dump]: initialization (1 / 1 reps)                                                                                                                                  
0.8646647167633873[dumpiness=very-dump]:   0.0% (1 …
```

FIX - remove debugging print left from PR#461

---

benchopt/tests/__init__.py
benchopt/tests/fixtures.py

As reported by @mathurinm , [this change](https://github.com/benchopt/benchopt/commit/4733a8f5a9f278353bfd4c98ba2de2a8d253ead6#diff-b02f52b735585c6cb5cf0d64f4a4031b464e42b9ddd51519faaa0edbba5310c4R9) broke the tests on all benchmark repos.
This PR fixes it.

FIX test command relative import

---

benchopt/benchmark.py
benchopt/cli/main.py
benchopt/tests/__init__.py
benchopt/tests/test_benchmark_features.py
benchopt/tests/test_benchmarks/dummy_benchmark/objective.py
benchopt/tests/test_benchmarks/future_benchmark/objective.py
benchopt/tests/test_cli.py

Define `min_benchopt_version` attribute in a benchmark to raise an error if the version of benchopt that is used it too old.

ENH min benchopt version

---

doc/names.inc
setup.cfg

With sphinx 5.0 I could not build the doc, as in https://github.com/alphacsc/alphacsc/pull/95
+ little fix to add @Melvin-klein 's name

DOC Pin sphinx version to 4.5.0 

---

benchopt/plotting/plot_objective_curve.py

FIX regression from `numpy==1.24.0` which broke compat with pandas.
This should be reverted once matplotlib/matplotlib#24773 is resolved.

FIX convert pandas to numpy for plot

---

benchopt/tests/test_benchmarks.py
benchopt/utils/dependencies_mixin.py
pyproject.toml
roadmap.md

Just got stuck because I added some requirements but it did not get installed... I think it make more sense to default to `install_cmd='conda'`

CLN default install_cmd to 'conda'

---

benchopt/plotting/generate_html.py
benchopt/plotting/html/static/result.js
benchopt/plotting/html/templates/result.mako.html
benchopt/runner.py

This adds a toggle to enable visualizing the objectives as function `stop_val`, namely ``n_iter``.
[Link to a dummy benchmark ](https://badr-moufad.github.io/share-benchmarks/stop_val_plot/validate-plotting-stop-val_benchopt_run_2022-11-09_20h57m17.html) to preview the feature. (credit to @mathurinm for the idea of the benchmark).
A link to the [benchmark repo ](https://github.com/Badr-MOUFAD/validate-plotting-stop-val) to reproduce.
-----------------------
PR related to #287

PLT - add visualization of objective as function of ``stop_val``

---

benchopt/plotting/generate_html.py
doc/names.inc
doc/whats_new.rst

After merging #479, we might have dropped the ability to replot previous benchmarks.
closes #545

PLT - preserve plotting for benchmark run in previous version

---

benchopt/benchmark.py

When running `benchopt plot --all`, the variable `result_filename` is a list and so hasn't a `suffix` attribute. This PR handle this case.

FIX detection of csv files when plotting with option --all

---

.github/workflows/release.yml

Fixes failure of "release on PyPI" action  in https://github.com/benchopt/benchopt/actions/runs/4935551334?pr=231 for example

MNT update ubuntu 18.04 to ubuntu-latest (20.04) in release action

---

benchopt/plotting/generate_html.py
benchopt/plotting/html/static/hover_index.css
benchopt/plotting/html/static/result.js
benchopt/plotting/html/templates/result.mako.html
benchopt/runner.py
doc/whats_new.rst

This adds a way of showing additional information about solvers when placing the cursor over them in the legend.
Here is a [preview of the features](https://badr-moufad.github.io/share-benchmarks/solver_description/validate-plotting-stop-val_benchopt_run_2023-03-08_17h46m44.html) that shows how the solvers' metadata would be displayed.
I see one limitation of this approach is the amount of content we can display.
-------------------
Also related to https://github.com/benchopt/benchopt/pull/523.

PLT - Show solver description when hovering over it

---

benchopt/plotting/generate_html.py

As observed in one case with @tomMoral this afternoon.
Here is the full traceback:
```
benchopt plot .
```
```python-traceback
Processing outputs/benchopt_run_2023-06-21_17h02m11.parquet
/Users/ogrisel/code/benchopt/benchopt/plotting/generate_html.py:216: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
groupby_stop_val_median = groupby_stop_val_median.median()
Traceback (most recent call last):
File "/Users/ogrisel/mambaforge/envs/dev/bin/benchopt", line 8, in <module>
sys.exit(benchopt())
^^^^^^^^^^
File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.11/site-packages/click/core.py", line 1130, in …
```

Fix exception in shape_solvers_for_html when objective column has all nan values

---

benchopt/plotting/generate_html.py
benchopt/plotting/html/static/hover_index.css
benchopt/plotting/html/templates/result.mako.html
benchopt/runner.py
benchopt/tests/test_benchmarks/dummy_benchmark/objective.py
doc/whats_new.rst

This adds the possibility to provide details about the objective metrics, for instance, value and support size.
It exposes an icon beside ``objective_column`` which when hovered shows a description of the objective metrics.
[Live preview of the feature](https://badr-moufad.github.io/share-benchmarks/prev_objective_desc/generated_df_lasso_bench.html).
------
revival of #523

PLT - Add objective description

---

benchopt/stopping_criterion.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/solver_test.py
doc/advanced.rst
doc/performance_curves.rst
doc/whats_new.rst

This enables accessing solvers parameters and attributes by making `get_next` a regular method instead of `staticmethod`
closes #564

ENH - make ``get_next`` a regular solver method

---

README.rst

Add link to software heritage archives of `benchopt`.
We might want to make it easy to archive the code of a benchmark that was used to produce the results from a paper?
TBD.

DOC add badge SWH

---

benchopt/tests/test_cli.py
benchopt/utils/dependencies_mixin.py

Added an error message in `install` method of `DependenciesMixin` class to make error `AttributeError: type object 'Solver' has no attribute 'requirements'` understandable.

Created error message for requirements error

---

README.rst

This adds a new line to the table with all benchmarks

ENH: add bilevel benchmark in readme

---

benchopt/plotting/html/static/hover_index.css

After https://github.com/benchopt/benchopt/pull/575, a bug slipped through that made the solver legend item span the entire available space.
This fixes this malfunction.

PLT - Fix solvers legend item vertically displayed

---

benchopt/base.py
benchopt/runner.py
doc/advanced.rst
doc/names.inc
doc/whats_new.rst

This changes how to warm up solvers that are, e.g., jitted.
Previously, the warm-up was done in `set_objective`, so the warm-up is done even if the algorithm has already been run and the results are cached; warm-up was the bottleneck when results were already cached.
Now, the solvers have a `warm_up` method specified by the user,  and the warm_up method is called on the first `run_one_to_cvg` call. Hence, the warm_up is also in the cached function, so not run when results are already cached.
Not sure about the best way to code this is:
So far I have a `_warm_up` method that calls warm up if the flag `Solver.warmup_done` is False/ does not exist, but it would maybe be more explicit to play with the flag in the `run_one_to_cvg` function, WDYT?

ENH: add a warm_up function in the solvers

---

.github/workflows/expose_link.yml

So far, CI doesn't expose the link to the documentation artifact.

FIX - Broken link to documentation artifact

---

README.rst

This updates the links pointing to documentation, after #619.
Also, it fixes the format

FIX - broken links in the README

---

benchopt/benchmark.py
benchopt/tests/test_benchmark_features.py

When working on remote machines (e.g. with sshfs), macos automatically creates hidden files.
For example, if there is a file `datasets/mnist.py`, then it automatically creates a metadata file `datasets/._mnist.py`.
Thus, benchopt loads `datasets/mnist.py` but also `datasets/._mnist.py` which creates errors since  `datasets/._mnist.py` only contains metadata. To prevent this, this PR changes the regex that loads submodules to ignore hidden files.

FIX ignore hidden files when loading datasets, solvers, etc

---

benchopt/base.py
benchopt/callback.py
benchopt/runner.py
benchopt/tests/test_benchmark_features.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_benchmarks/dummy_benchmark/doc_objective.py
benchopt/tests/test_benchmarks/dummy_benchmark/objective.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/python_pgd_callback.py
benchopt/tests/test_benchmarks/requirement_benchmark/objective.py
benchopt/tests/test_benchmarks/requirement_benchmark/solvers/baseline.py
benchopt/tests/test_runner.py
doc/benchmark_workflow/write_benchmark.rst
doc/user_guide/performance_curves.rst
doc/whats_new.rst

This fixes the fact that `BaseObjective` was not raising error if an abstractmethod is not implemented.
It also makes the backward compatibility between `compute/evaluate_result` work with results that are dictionaries.
Finally, it renames `Objective.get_one_solution` into `Objective.get_one_result`.

FIX abstract classes in BaseObjective

---

benchopt/plotting/html/templates/result.mako.html

In the dashboard of results, the meaning of the **objective column** isn't very clear.
This suggests renaming it to **Objective metrics**.
pining @mathurinm

MNT - rename objective column to objective metrics

---

doc/conf.py

The PR #635 showed that syntax highlighting in code blocks is a bit confusing,
namely, the color of comment is the same as ``self``
This changes the theme to a more suitable one.

DOC - more clear syntax highlighting in code blocks

---

benchopt/base.py
benchopt/tests/test_benchmark_features.py

This fixes #642.
The `warm_up` method was not called when the attribute `_warmup_done` did not exist.

FIX call `warm_up` when the attribute `_warmup_done` don't exist

---

benchopt/plotting/generate_html.py

Fix legend that was not displayed on same cases. The problem was due to the fact that the legend colours were not reset when the `generate-results` command was run.
It works but I have to check if some code is now outdated.
@tomMoral

Fix HTML legend that was not displayed on some cases.

---

benchopt/tests/test_benchmark_features.py
setup.cfg

The test are failing following the latest release of pytest.
As a mitigation, I just pinned `pytest<7.4.1`
The issue seems to be with an internal in `pytest` from a call to the function `_early_rewrite_bailout` that  gives this error from l.203:
```
$ benchopt test /tmp/tmpdqk7v3vc -- -k test_benchmark_objective
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.10.9, pytest-7.4.2, pluggy-1.0.0
project deps: mylib-1.1
rootdir: /home/tom/Work/prog/benchopt/benchopt/tests
plugins: anyio-3.6.2, timeout-2.1.0, typeguard-2.13.3, cov-4.0.0
collected 35 items / 34 deselected / 1 …
```

FIX pinnig pytest for now

---

benchopt/base.py
benchopt/tests/test_benchmark_features.py
benchopt/tests/test_benchmarks.py

In benchopt/benchmark_ot#4, failures appears because `pre_run_hook` is not called before `run` in the test.
This PR makes sure `pre_run_hook` is always called before `run` in benchopt.
It also changes the tests to use `Solver.run_once` in `test_solver` instead of a custom implementation.
I will add a test with a `pre_run_hook` before merging this PR.

FIX call pre_run_hook in run_once

---

doc/whats_new.rst

Bugfix release following up on #662 .
This release should fix the failures on all the benchmarks CI for workflow with the released version of benchopt.

RELEASE bugfix v1.5.1

---

benchopt/benchmark.py
benchopt/cli/helpers.py
benchopt/runner.py
benchopt/utils/slurm_executor.py

Fixes #664 
The command ```benchopt clean``` now cleans the content of the ```benchopt_run``` directory if it exists (for SLURM submissions).

FIX clean benchopt_run

---

benchopt/utils/shell_cmd.py

Running shell commands through benchopt doesn't work with the fish shell at the moment.
This commit checks if fish is in use and modifies the call appropriately.
There's also a small change for the input to `subprocess.getstatusoutput`, which was a list but should be a string (according to the docs), but it's working anyway so I guess it's a cosmetic change.

ENH add support for fish shell

---

.circleci/config.yml
.github/workflows/test.yml

Temporary fix as 1.10.1 seems to have broken some downloads functionalities : https://github.com/JuliaLang/julia/issues/53339, causing the tests to fail on `main`: https://github.com/benchopt/benchopt/actions/runs/8018415344/job/21904251404#step:6:1302

FIX pin julia version to <=1.10.0

---

benchopt/tests/fixtures.py
setup.cfg

Config flake8 to ignore `benchmarks` folder and add option to skip tests which require creating a conda env and are slow.

MTN config flake8+skip conda env test

---

benchopt/base.py
benchopt/runner.py
benchopt/stopping_criterion.py
benchopt/tests/test_stopping_criterion.py
setup.cfg

Fix the regression introduced in #623 with `run_once` and add some non-regression tests.
This should fix the failures seen on [benchopt/benchmark_bilevel](https://github.com/benchopt/benchmark_bilevel)

FIX sampling strategy priority

---

benchopt/benchmark.py
setup.cfg

`joblib1.4` introduced a beaking change that `MemorizedFunction.call` doesn't return the metadata anymore.
This adapt to this change and bump the necessary version of joblib.

MTN adapt to joblib 1.4

---

benchopt/base.py
benchopt/plotting/html/templates/benchmark.mako.html
benchopt/stopping_criterion.py
benchopt/tests/test_benchmarks.py

- Improve stopping_criterion error on bad keys
- Fix rendering failure when `]` in objective name
- FIX make sure to call `get_objective` before calling `get_one_result` (to make sure `get_split` is called)

CLN various cleanups

---

benchopt/utils/safe_import.py
benchopt/utils/temp_benchmark.py
benchopt/utils/tests/test_dynamic_module.py
doc/whats_new.rst

Follow up of #712 which was merged a bit quickly.
This should fix the issue in scikit-adaptation/skada-bench#60 with missing `benchmark_utils` module.

FIX benchmark_utils pickling

---

benchopt/benchmark.py
benchopt/cli/helpers.py
benchopt/cli/main.py
benchopt/cli/tests/test_cli.py
benchopt/cli/tests/test_helpers.py
benchopt/utils/dependencies_mixin.py
doc/whats_new.rst

In some cases, we want to make sure the data is properly loaded when installing the benchmark, by calling `get_data` on certain datasets.
This PR adds a `--download` flag to `benchopt install` to allow calling `get_data` on any installed datasets.
This is useful in particular on big cluster where internet is not available on the computing nodes, or to avoid multiple process all trying to download the data at the same time.

ENH download data

---

.github/workflows/release.yml

See warning message here : https://github.com/benchopt/benchopt/actions/runs/9346497454/job/25721464718#step:9:49
```
You are using `pypa/gh-action-pypi-publish@master`. The `master` branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use `pypa/gh-action-pypi-publish@release/v1`. If you feel adventurous, you may opt to use use `pypa/gh-action-pypi-publish@unstable/v1` instead.
```

MNT update pypa action tag

---

.github/workflows/expose_link.yml
.github/workflows/linting.yml
.github/workflows/test.yml

In a PR, each push executes continuous integration tests; however, if you commit and push multiple times within a PR, you create a queue of jobs and testing.
If you have tests that take longer, this ends up generating a long queue to have one test done. This is meaningless, as we always want to test only the last commit.
In this PR, we ensure that CI stops the tests for the previous push and runs the test only for the last one.

MNT Execute only the last push commit in CI

---

benchopt/base.py
benchopt/runner.py
benchopt/tests/test_benchmark_features.py
doc/faq.rst
doc/names.inc
doc/user_guide/advanced.rst
doc/whats_new.rst

Hey there ! 
This PR add the possibility to save the final results of a benchmark to the filesystem. The data is saved as a `.pkl` file and a reference is added to the metadata of the benchmark. 
This is a much need capability for imaging problems, where getting visualisation of the results is complementary of quantitative metrics (PSNR, SSIM). 
It also opens the possibility to perform further processing on solver outputs (computing extra metrics, statistics, etc.)

Saving final results of a solver

---

.github/workflows/test.yml

This PR should be merged once JuliaLang/julia#53339 is solved.

MTN unpin julia version

---

benchopt/cli/main.py
benchopt/cli/tests/test_cli.py
benchopt/runner.py
benchopt/tests/fixtures.py
benchopt/tests/test_benchmark_features.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_objective_outputs.py
benchopt/tests/test_run_config_files.py
benchopt/tests/test_runner.py
benchopt/tests/test_stopping_criterion.py
doc/user_guide/advanced.rst
examples/plot_run_benchmark.py
examples/plot_run_benchmark_python_R.py

It is sometimes useful to be able to run benchopt from a script, in particular to debug part of the code.
This feature was broken by #706.

ENH improve running benchopt in a script

---

benchopt/benchmark.py
benchopt/cli/helpers.py
benchopt/cli/tests/test_cli.py
benchopt/helpers/julia.py
benchopt/utils/conda_env_cmd.py
benchopt/utils/dependencies_mixin.py
benchopt/utils/tests/test_conda_env_cmd.py
doc/benchmark_workflow/install_benchmark.rst

when specifying a channel with a URL, the `:` split breaks;
This PR changes this to get `::` instead to desambiguate.
TODO:

ENH replace channel specification from : to :: to accomodate url

---

benchopt/tests/__init__.py
benchopt/tests/dummy_benchmark/solvers/solver_test.py
benchopt/tests/test_runner.py
benchopt/tests/utils/capture_run_output.py
benchopt/utils/terminal_output.py
doc/whats_new.rst

The current implementation of the `skip` API fails when skipping some objective, because of bad interactions with the terminal_output.
This PR fixes the issue and adds better tests for the full pipeline, including reporting.
cc @ceelestin

Fix skip objective

---

benchopt/cli/helpers.py
doc/whats_new.rst

running `benchopt info` resulted in error because `validate_*` functions have been renamed to `check_*`
-------
- ~~[ ] added documentation for any new feature~~
- ~~[ ] added unit test~~

FIX: use correct function in "benchopt info"

---

benchopt/tests/test_deprecation.py
benchopt/utils/conda_env_cmd.py
benchopt/utils/tests/test_conda_env_cmd.py

The current use of `PIP_CMD` which use `sys.executable` does not point toward `python` in the right environment. As using only `pip` can cause issues on windows, I propose to create an environment file with both `conda` and `pip` deps and install everything in one go with [`conda env update`](https://docs.conda.io/projects/conda/en/latest/commands/env/update.html)

FIX installing pip dependencies in conda environment

---

.circleci/config.yml

CI update to use miniforge instead of mambaforge in install

---

benchopt/utils/conda_env_cmd.py

With #772, we use a more complicated way to install in conda env, which is currently broken when installing in the current env. It actually creates a `None` env and install everything to it.
This PR fixes this behavior.

FIX install in current env

---

benchopt/plotting/html/static/hover_index.css
benchopt/plotting/html/templates/index.mako.html

Fix the following css bug of the result web page as shown in the screen below.
Removed an old image reached by its URL that is not available anymore and frozen the height of items with the same height as the old image.

Fix result page css

---

benchopt/benchmark.py
benchopt/cli/main.py
benchopt/tests/test_install.py
benchopt/tests/test_runner.py
benchopt/utils/dependencies_mixin.py
doc/whats_new.rst

Useful to have both gpu/cpu requirements, and avoid having dynamically defined `Solver.requirements`, which is blocking for #788

API support requirements as dict

---

.github/workflows/test.yml
benchopt/base.py
benchopt/callback.py
benchopt/plotting/plot_boxplot.py
benchopt/runner.py
benchopt/stopping_criterion.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_objective_outputs.py
doc/conf.py
doc/sg_execution_times.rst
doc/user_guide/advanced.rst
doc/user_guide/performance_curves.rst
doc/whats_new.rst

In some cases, we want to be able to flatten the objective output and produce multiple values in the dataframe at once.
This PR allows `Objective.evaluate_result` to output a dict or a list of dict, that are extended with the meta data and appended in the result dataframe.

ENH allow objective to produce multiple entries at once

---

benchopt/benchmark.py

When the parameter space is too large but each run is very fast, we can have a bottleneck in generating the list of parameters.
This PR avoids this by not creating the list but consuming the parameters as they come.

FIX slow parallel run when large parameter space

---

.github/workflows/test.yml
benchopt/utils/slurm_executor.py
benchopt/utils/temp_benchmark.py
benchopt/utils/tests/test_slurm_executor.py
doc/user_guide/advanced.rst
doc/whats_new.rst

This PR enables solver-specific overriding of the global `--slurm` config by adding a new `slurm_params` keyword. The syntax is as follows:
```python
class Solver(BaseSolver):
"""GPU-based solver that needs GPU partition and specific resources."""
name = 'GPU-Solver'
parameters = {...}
slurm_params = {
'slurm_partition': 'gpu',
'slurm_gres': 'gpu:1',
'slurm_time': '02:00:00',
'slurm_cpus_per_task': 8,
'slurm_mem': '16GB',
}
requirements = ['torch']
def set_objective(self, X, y):
...
```
TODO:

[ENH] Add solver-specific overrides for SLURM executor configuration

---

benchopt/utils/slurm_executor.py
benchopt/utils/tests/test_slurm_executor.py

In #805 , we did not consider the case where `slurm_config` contains some complex arguments, like `slurm_additional_parameters` which is usually a dict.
This PR tests this case and fix the behavior to make the argument hashable.
Previous behavior resulted in the following error:
```    
executor_config = tuple(sorted(solver_slurm_config.items()))
>               if executor_config not in executors:
E               TypeError: unhashable type: 'dict'
benchopt/utils/slurm_executor.py:84: TypeError
```

FIX slurm_config can contain dict

---

.circleci/config.yml

In PR #787, I get the following error of the installation of miniconda (circle ci step: Get conda running)
```
ERROR: File or directory already exists: '/home/circleci/miniconda'
If you want to update an existing installation, use the -u option.
Exited with code exit status 1
```
The error is due to that the cache is based on a previous version of conda.

CI fix broken install of conda due to existing directory in cache

---

benchopt/utils/sys_info.py

FIX: split sys info for numpy in parquet file

---

.github/workflows/test.yml
benchopt/cli/tests/test_cmd_test.py
benchopt/tests/__init__.py
benchopt/tests/fixtures.py
benchopt/utils/conda_env_cmd.py
doc/whats_new.rst

A regression introduce in #673 make running `benchopt test` in an environment without `pytest` fails.
This PR fixes this and adds some non-regression test

FIX benchopt test no pytest
