benchmarks/logreg/solvers/celer.py

Celer's API has changed in the dev version (merged `celer_path` and `logreg_path`), so I updated the related code

ENH update in celer API for logreg

---

benchmarks/lasso/datasets/boston.py
benchmarks/lasso/datasets/simulated.py
benchmarks/lasso/solvers/blitz.py
benchmarks/lasso/solvers/sklearn.py
benchmarks/logreg/solvers/blitz.py
benchmarks/logreg/solvers/sklearn.py
benchopt/base.py
benchopt/cli.py
benchopt/config.py
benchopt/runner.py
benchopt/tests/test_benchmarks.py
benchopt/util.py
setup.py

Some datasets requires dependencies to download the data. They should not be part of the global deps of the package.
This PR extend the install mechanisms to datasets

ENH add deps installation for datasets

---

README.md

Time to go back on benchOpt folks ;)

improve README by listing the problems of interest

---

benchmarks/lasso/solvers/cd.py
benchmarks/nnls/solvers/cd.py

addresses issue #35 raised by @josephsalmon 
@agramfort this one is easy to review :)

[MRG] skip 0 columns in cd

---

README.rst

This is to improve the README, and correct some minor error (wrong n/n_samples factor in the objective)

cosmit +  n_samples isues corrected in README

---

benchmarks/lasso/solvers/cd.py
benchmarks/nnls/solvers/cd.py
benchmarks/ols/solvers/cd.py

adding @mathurinm propositio to remove linalg.norm in cd.py by substituting (x)**2.sum(axis =0) to linalg.norm(x)

CLN better computations for L constants in cd

---

.gitignore
README.rst
benchmarks/lasso/solvers/blitz.py
benchmarks/lasso/solvers/celer.py
benchmarks/lasso/solvers/cvxpy.py
benchmarks/lasso/solvers/julia_pgd.py
benchmarks/logreg_l1/solvers/blitz.py
benchmarks/logreg_l1/solvers/celer.py
benchmarks/logreg_l1/solvers/cvxpy.py
benchmarks/logreg_l1/solvers/liblinear.py
benchmarks/nnls/solvers/nnls_scipy.py
benchopt/base.py
benchopt/cli.py
benchopt/config.py
benchopt/runner.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_cli.py
benchopt/util.py
benchopt/utils/checkers.py
benchopt/utils/dynamic_modules.py
benchopt/utils/julia.py
benchopt/utils/shell_cmd.py
benchopt/utils/stream_redirection.py
benchopt/viz.py
continuous_integration/install.sh
continuous_integration/test_script.sh
doc/index.rst
examples/plot_run_benchmark.py

With this PR, the `benchopt` client should be provided with a folder in which the benchmark is defined:
```bash
benchopt run benchmarks/lasso
```

ENH run benchmarks from any folders

---

Makefile
benchopt/utils/shell_cmd.py

For some reason I could not activate the conda environment from a script.
This fixes the issue, cf https://github.com/conda/conda/issues/7980.
I also added a Makefile recipe to clean conda environment.

FIX execute conda activate from script

---

doc/how.rst

We need to improve a bit the how to I think. Don't hesitate to read it and to make suggestions.

DOC improve the how to make a benchmark

---

benchmarks/lasso/solvers/python_pgd.py

Comparison of the 2 implems:
closes #60

FIX APGD implementation

---

doc/how.rst

FIX urls in how.rst

---

MANIFEST.in
benchopt/cli.py
benchopt/tests/__init__.py
benchopt/tests/test_benchmarks/dummy_benchmark/datasets/simulated.py
benchopt/tests/test_cli.py
benchopt/utils/checkers.py
benchopt/utils/datasets/simulated.py
benchopt/utils/datasets/tests/test_dataset_simulated.py
benchopt/utils/shell_cmd.py
doc/api.rst

Addressing #21, but it takes a long time (> 3 mins) to generate the data now (my guess is that an EVD of correlation matrix is performed, the later being 10k x 10k in some cases)

ENH helper for non diagonal covariance in simulated

---

benchopt/runner.py

Replace forbidden character in name file for Windows.
The timestamp is now Year-month-day_HourhMinutemSeconds.

[CLN] replace : in filename

---

benchopt/base.py
benchopt/cli.py
benchopt/runner.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_benchmarks/dummy_benchmark/objective.py
benchopt/tests/test_cli.py
benchopt/util.py
benchopt/utils/checkers.py
benchopt/utils/colorify.py
benchopt/utils/pdb_helpers.py
benchopt/viz/__init__.py
benchopt/viz/helpers.py
benchopt/viz/plot_convergence_curve.py
benchopt/viz/plot_histogram.py

Objective can now return a dictionary with multiple values that will be recorded.
this allow to monitor different metrics to display in the results.

ENH allow multi output objective

---

benchopt/runner.py

When all solver output an error, you have a weird, uncomprehensible error.
This PR intend to make it more comprehensible.

FIX more comprehensible error on no output

---

benchopt/cli.py

Set the default for `benchopt run` to be in local env.
Also add a more rational API to decide where to run the benchmark.

ENH default run in local env+improve env API

---

benchopt/base.py
benchopt/runner.py
benchopt/tests/test_benchmarks/dummy_benchmark/doc_objective.py
benchopt/viz/plot_convergence_curve.py
benchopt/viz/plot_histogram.py
doc/how.rst

Add some explanations about the multi output (especially the NaNs in the dataframe).

add some doc and split test-doc

---

benchopt/cli.py
benchopt/config.py
benchopt/viz/__init__.py
benchopt/viz/plot_objective_curve.py
benchopt/viz/plot_optimality_curve.py
benchopt/viz/plot_suboptimality_curve.py
examples/plot_run_benchmark.py
examples/plot_run_benchmark_python_R_julia.py

instead of `convergence_curve`, I created 3 types of plots without modifying the saved df
- `suboptimality_curve` : $F(x) - F(x*)$, the default one
- `relative_suboptimality_curve` : $(F(x) - F(x*)) / (F(x^0) - F(x*))$
- `optimality_curve` : $F(x)$

Add relative suboptimality, suboptimality and optimality plots

---

.github/workflows/linting.yml
benchopt/utils/r_helpers.py

Allow to use LAPACK library for the SVD with Anaconda rpy2 installation or other if Anaconda didn't replace it

Fix PGD with R (LAPACK import)

---

.coveragerc
benchopt/base.py
benchopt/runner.py
benchopt/utils/parametrized_name_mixin.py

Some clean up on the way we handle parameters in the base class.

CLN base.py and coverage report

---

benchopt/plotting/plot_objective_curve.py

Scientific notation on yscale instead of "physician" one

format scale convergence curve

---

benchopt/plotting/helpers_compat.py
benchopt/plotting/plot_objective_curve.py

This is to solve issues on the numbers of colors used for the plotting.
Adding markers will help to discriminate, and also increases the number of possible of possibility.
One issue though, it might requires some tweaking to have sames order of markers in plotly and matplotlib.
Examples are attached.

[ENH] adding markers to plots

---

.gitignore
benchopt/base.py
benchopt/runner.py
benchopt/tests/__init__.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_benchmarks/dummy_benchmark/datasets/dataset_test.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/cd.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/python_pgd.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/r_pgd.R
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/r_pgd.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/solver_test.py
benchopt/tests/test_cli.py
benchopt/tests/test_runner.py
doc/_static/style.css
doc/_templates/autosummary/class.rst
doc/whats_new.rst
setup.py

- Add skip API to avoid long runners.
- Rename `scale` to `dimension`
- Add some test for the runner.

ENH skip api

---

benchopt/utils/github.py

For non-commiter on `benchopt/benchopt`, `benchopt publish` now create a PR automatically.

ENH publish for non-commiter create a PR

---

benchopt/cli.py

Corrects the `help` of plot kinds and closes #124

DOC change doc plot kinds

---

README.rst
doc/index.rst

clarify doc

---

benchopt/cli/completion.py
benchopt/cli/helpers.py
benchopt/cli/main.py
benchopt/cli/process_results.py

Some improvement on the auto completion.

ENH improved auto-completion

---

.circleci/config.yml
.github/workflows/release.yml
.gitignore
MANIFEST.in
benchopt/__init__.py
benchopt/utils/safe_import.py
continuous_integration/install.sh
dev-requirements.txt
doc/doc-requirements.txt
examples/plot_run_benchmark.py
pyproject.toml
setup.cfg
setup.py

This PR auto-release on to test-pypi with push on `master` and releases on pypi for tags.
The issue here is that it requires bumping the version number for each push on master.
This PR should not be merged before a solution is chosen (either auto bumping or no release on test-pypi).

[MRG] MTN autorelease to pypi on tags

---

benchopt/tests/test_benchmarks.py

I replaced np.zeros(*dimension) by np.zeros(dimension) in test_benchmark_objective to handle multidimensional shapes output by dataset.get_data().

FIX: Fixing an issue with the dimension in test_benchmark_objective

---

benchopt/benchmark.py
benchopt/cli/completion.py
benchopt/cli/helpers.py
benchopt/cli/main.py
benchopt/runner.py
benchopt/tests/__init__.py
benchopt/tests/conftest.py
benchopt/tests/test_benchmarks.py
benchopt/utils/conda_env_cmd.py
benchopt/utils/dependencies_mixin.py
benchopt/utils/parametrized_name_mixin.py

Install all deps in one shot in `benchopt install`.

ENH allow to install all the benchmark in one shot

---

.circleci/config.yml
doc/Makefile
examples/plot_run_benchmark.py
examples/plot_run_benchmark_python_R_julia.py

solves #183 
adding a README in the `doc/` folder should also help

MRG: syncing  benchmark repos in makefile before make html

---

benchopt/cli/main.py
benchopt/runner.py

added option to get matplotlib figures instead of html after run

add option no_html

---

.circleci/config.yml
benchopt/benchmark.py
benchopt/tests/__init__.py
benchopt/tests/test_cli.py
doc/index.rst

the many calls to replace are unsatisfying  but short, readable and not in a part of the code which is speed critical
closes #178

ENH: make benchopt run . -s solver[option=12]   work

---

benchopt/base.py
benchopt/plotting/__init__.py
benchopt/plotting/generate_html.py
benchopt/plotting/html/templates/result.mako.html
benchopt/plotting/plot_histogram.py
benchopt/plotting/plot_objective_curve.py
benchopt/tests/test_benchmarks/dummy_benchmark/doc_objective.py
benchopt/tests/test_benchmarks/dummy_benchmark/objective.py
doc/how.rst
doc/whats_new.rst

Add a prefix to all `objective` outputs and then print all of them so we can have multiple curves.

ENH multi objective plotting

---

benchopt/plotting/html/static/hover_index.css
benchopt/plotting/html/templates/benchmark.mako.html
benchopt/plotting/html/templates/index.mako.html
benchopt/plotting/html/templates/result.mako.html
benchopt/plotting/plot_objective_curve.py

Now, for each dataset the user does not have to change the axis type (loglog or semilog) when switching plots / hyperparameters.
This is an issue @mathurinm raised to me and it is more convenient for users.
Also, I took advantage of returning into these parts of the code to remove some warnings/uncaught exceptions that were displayed in the js console.

Scaling axis once for all plotly

---

benchopt/plotting/generate_html.py
benchopt/plotting/html/templates/benchmark.mako.html

for some reason this does not work
help welcome @tanglef 
basically I want to see the latest results appear first

descending order based on date

---

benchopt/plotting/html/static/result.js
benchopt/plotting/html/templates/result.mako.html

Fixes #222 by adding semilog-x and linear graph axis types (poke @mathurinm )

Add axis types semilog and linear

---

benchopt/runner.py

From:
```
|----glum: initialization (0 / 3 reps)                                        
|----glum:   0.0% (0 / 3 reps)                                                
|----glum:   1.0% (0 / 3 reps)                                                
|----glum:   2.0% (0 / 3 reps)                                               
```
To:
```
|----glum: initialization (1 / 3 reps)                                     
|----glum:   0.0% (1 / 3 reps)   
```

fix n repetitions in display bar

---

benchopt/plotting/plot_objective_curve.py

closes #238 
I was ending up with 16 figures without knowing which was which. 
also related to #239 : relative suboptimality for test loss may not be relevant

display name of objective on the ylabel when --no-html

---

benchopt/benchmark.py
benchopt/cli/main.py
benchopt/utils/conda_env_cmd.py

I also set capture_stdout to False, even without CONDA_DEBUG since env creation takes a long time and people want feedback e.g. #90 
Fix #241

fix channels priorities

---

benchopt/plotting/__init__.py

closes #245 
I do this because I don't think we know what convergence means for a value which is not the minimized objective.

plot histogram only for objective_value

---

benchopt/benchmark.py
benchopt/cli/main.py
benchopt/utils/conda_env_cmd.py

finishes what was started in #244

Quiet flag in dependencies install

---

.circleci/config.yml

Replace all mentions of master as main in `.circleci/config.yml`

Circle ci with main instead of master

---

benchopt/plotting/helpers_compat.py
benchopt/plotting/html/static/hover_index.css
benchopt/plotting/html/static/result.js
benchopt/plotting/html/templates/result.mako.html

This introduces a button to toggle on/off the shaded areas (and thus resolves #228 )
| On | Off |
:----------------------:|:------------------------------:

Toggle shaded areas

---

benchopt/benchmark.py
benchopt/cli/main.py
benchopt/utils/parametrized_name_mixin.py
examples/plot_run_benchmark_python_R.py

All permutations of parameters values are displayed when filters don't match objective attributes. However, I'm not sure of the format of the pattern...
Fixes #224

ENH list all possible objectives when unmatched pattern option is passed to -p

---

.circleci/config.yml
LICENSE
README.rst
benchopt/cli/__init__.py
setup.cfg

remove old occurrences of benchOpt, rm test in readme.rst

---

benchopt/cli/completion.py
benchopt/cli/helpers.py
benchopt/cli/main.py
benchopt/cli/process_results.py
benchopt/tests/test_cli.py
doc/cli.rst

Does it fix your issue @mathurinm ?

DOC fix autocomplete documentation

---

MANIFEST.in
doc/_templates/search.html

Fixes #271 by adding the proposed html file.

[Doc] Search bar with bootstrap theme

---

benchopt/tests/test_benchmarks.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/solver_test.py

Fix issue that causes failure in benchopt/benchmark_lasso#56.

TST fix check that get_next is a static method

---

benchopt/stopping_criterion.py
benchopt/tests/test_benchmarks.py

The changes in #274 broke the tests for many benchmarks.
This PR fixes it.

FIX stop_strategy deprecation

---

setup.cfg

fix typo in click version

---

benchopt/cli/helpers.py
doc/names.inc
doc/whats_new.rst

plus a little fix for @bmalezieux's name

DOC cosmit benchopt info -h output + update whatsnew

---

README.rst

old link has `master` and even replacing with `main`, it did not work.

fix install from github

---

benchopt/base.py
benchopt/benchmark.py
benchopt/cli/helpers.py
benchopt/cli/main.py
benchopt/tests/__init__.py
benchopt/tests/fixtures.py
benchopt/tests/test_benchmarks/requirement_benchmark/datasets/simulated.py
benchopt/tests/test_benchmarks/requirement_benchmark/objective.py
benchopt/tests/test_benchmarks/requirement_benchmark/solvers/baseline.py
benchopt/tests/test_cli.py
benchopt/utils/dependencies_mixin.py
benchopt/utils/dynamic_modules.py

This PR intends to add support for `requirements` in benchmarks' `Objective`.
Fixes #306

ENH requirements for bench's Objective

---

benchopt/plotting/html/static/hover_index.css
benchopt/plotting/html/static/main.css
benchopt/plotting/html/templates/result.mako.html

- make the home button the same height as other buttons
- move the download button above the title
- reduce size of switch slider
___
Before:
___
After:

Improve the layout of the result webpage

---

benchopt/plotting/html/static/benchmark.js
benchopt/plotting/html/static/main.css
benchopt/plotting/html/templates/benchmark.mako.html
benchopt/plotting/html/templates/result.mako.html

This PR removes the sidebar, and add dropdown selectors matching "Select X entries".
It also change the sysinfo names to uppercase ("cpu" --> "CPU").
Fixes #318
___
**Before**
___
___
**After**
___

ENH remove the sidebar in the benchmark result homepage

---

benchopt/cli/main.py

closes #329 
@jolars can you give it a try ?

FIX usage of deprecated -p flag when running bench in env

---

benchopt/utils/github.py

Always create a PR with `publish`

Remove push rights on publish

---

benchopt/base.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_benchmarks/dummy_benchmark/datasets/dataset_test.py
benchopt/tests/test_benchmarks/dummy_benchmark/objective.py
benchopt/tests/test_runner.py

Change name to be clearer, cc @pierreablin.
fixes #351

CLN rename get_one_beta -> get_one_solution

---

doc/index.rst

Correct way to get latest dev version in the doc

[DOC] Dev release command pypi

---

benchopt/tests/test_benchmarks/dummy_benchmark/test_config.py

Still not able to run on OSX but all good for linux (improve coverage cf #359)

Only skip julia on OSX

---

benchopt/cli/main.py

Should fix #366 , cc @mathurinm

FIX escape brackets in command line when running in env

---

doc/cli.rst
doc/whats_new.rst

DOC add changelog entry

---

benchopt/benchmark.py
benchopt/tests/test_runner.py

Fixes #379 by allowing dots in names

allow dots in names

---

.gitignore
doc/cli.rst
doc/conf.py
doc/contrib.rst
doc/index.rst
setup.cfg

Add contrib to doc 

---

benchopt/plotting/html/templates/benchmark.mako.html
benchopt/plotting/html/templates/index.mako.html

Results webpages didn't have the modifications yet

Remove last Os from BenchOpt to Benchopt

---

benchopt/utils/sys_info.py

@Badr-Moufad I tested on windows and it fixed the problem you had (that I could reproduce)

FIX use redirect_stdout in get_sys_info for windows

---

README.rst
benchopt/cli/main.py
benchopt/cli/process_results.py
doc/_static/style.css
doc/advanced.rst
doc/api.rst
doc/cli.rst
doc/conf.py
doc/contrib.rst
doc/index.rst

A bunch of improvements for the website (see each commit).
In particular, it makes the sidebar more compact and with larger indents:
before:![image](https://user-images.githubusercontent.com/11065596/168407956-c4099cb2-32dc-4ab1-bd86-d3397a93a5ce.png)after:![image](https://user-images.githubusercontent.com/11065596/168407949-f134f863-a5ca-4966-b2e3-29f38e48eb9b.png)

Website improvements

---

benchopt/cli/completion.py
benchopt/cli/helpers.py
benchopt/cli/main.py
benchopt/cli/process_results.py
benchopt/tests/test_cli.py

Fixes #382
Not exactly sure how to test this though....

ENH use current working directory as default in CLI

---

benchopt/utils/terminal_output.py

BUG - fix ANSI colors in Windows

---

benchopt/cli/completion.py
benchopt/tests/test_cli.py

FIX autocompletion for paths

---

benchopt/utils/github.py

Fix parquet file publishing

---

benchopt/base.py
benchopt/tests/test_benchmarks/dummy_benchmark/doc_objective.py
doc/how.rst

Try to better explain the need for `get_one_solution`.
cc @cohenjer.

DOC improve the how to doc

---

.circleci/config.yml

Fixes the issue with building the doc in circleCI

CI create new env to avoid issue with pin python version in base env

---

benchopt/cli/process_results.py
benchopt/plotting/generate_html.py
benchopt/plotting/html/templates/benchmark.mako.html
benchopt/plotting/html/templates/index.mako.html
benchopt/plotting/html/templates/result.mako.html

Follow up PR on #432 to embed all static files in HTML and never count on `static` directory.
Fixes #291 
Closes #294

CLN embed all static files in html

---

benchopt/datasets/simulated.py

X_density and snr should be floats in make_correlated_data(). Let's be explicit about it.

FIX use floats for X_density and snr

---

benchopt/tests/__init__.py
benchopt/tests/fixtures.py
benchopt/utils/conda_env_cmd.py

Introduce a new synthax to add a channel for conda requirements with `channel:package`.
closes #477

ENH specify channel for conda reqs

---

.coveragerc
benchopt/utils/tests/test_conda_env_cmd.py

TST add conda requirements cmd generation

---

benchopt/base.py
benchopt/tests/test_benchmarks/dummy_benchmark/doc_objective.py
benchopt/tests/test_benchmarks/dummy_benchmark/objective.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/python_pgd.py
benchopt/tests/test_benchmarks/requirement_benchmark/objective.py
doc/how.rst

API deprecate `Objective.to_dict` in favor of `Objective.get_objective`

---

doc/names.inc
doc/whats_new.rst

We should stop forgetting the what's new entry :)

DOC add missing what's new entry

---

.github/workflows/test.yml
benchopt/benchmark.py
benchopt/tests/__init__.py
benchopt/tests/fixtures.py
benchopt/tests/test_benchmark_features.py
benchopt/tests/test_benchmarks/dummy_benchmark/benchmark_utils/import_error.py
benchopt/tests/test_benchmarks/dummy_benchmark/benchmark_utils/value_error.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/import_error_solver.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/value_error_solver.py
benchopt/tests/test_benchmarks/dummy_benchmark/test_config.py
benchopt/tests/test_cli.py
benchopt/utils/dependencies_mixin.py
benchopt/utils/stream_redirection.py

Better report error in solver/dataset import

ENH improve error reporting in solvers

---

benchopt/utils/safe_import.py

kudos to @AmelieVernay for spotting this

FIX AttributeError: module 'warnings' has no attribute 'FutureWarning'

---

benchopt/plotting/html/static/result.js

FIX scale down quantiles in JS

---

benchopt/stopping_criterion.py
benchopt/tests/test_stopping_criterion.py

API rename cost_curve in objective_list

---

.github/workflows/linting.yml
.github/workflows/release.yml
.github/workflows/test.yml

See warnings here for the `linting` action

MTN update action to v3 to use node 16

---

benchopt/callback.py
doc/convergence_curves.rst
doc/index.rst

DOC add page on curve sampling and stopping criterion

---

benchopt/cli/main.py
benchopt/tests/test_cli.py
doc/whats_new.rst

related to @jeandut suggestion in #531

FEAT syntactic sugar for timeout

---

README.rst

[Link to preview](https://github.com/Badr-MOUFAD/benchopt/tree/discord-badge#readme)

FIX - Discord badge in ``README``

---

doc/advanced.rst
doc/index.rst
doc/performance_curves.rst

I think the terms "computational budget" and "performance curves" are clearer to explain how the curves are samples.
Let me know what you think @mathurinm :)

DOC better explain computational budget

---

benchopt/utils/dependencies_mixin.py

This close #553 by clarifying skips of classes (Objective, Solver, Dataset) installation.
Preview:

ENH - CLI installation messages for uninstalled solvers

---

benchopt/base.py
benchopt/cli/main.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_benchmarks/dummy_benchmark/datasets/dataset_test.py
benchopt/tests/test_benchmarks/dummy_benchmark/objective.py
benchopt/tests/test_cli.py
benchopt/tests/test_runner.py
benchopt/utils/safe_import.py
doc/index.rst
doc/whats_new.rst

Prepare for release 1.4 by updating the what's new and removing deprecated patterns.

RELEASE v1.4.0

---

benchopt/plotting/html/static/result.js

This broke the possibilty to put `Iteration` as the x axis.

FIX trailing stopping_strategy

---

benchopt/base.py
benchopt/tests/test_benchmarks.py
benchopt/tests/test_benchmarks/dummy_benchmark/solvers/r_pgd.py
doc/whats_new.rst

MNT deprecate `Solver.support_sparse`

---

.gitignore
benchopt/utils/parquet.py
benchopt/utils/tests/test_parquet.py
doc/whats_new.rst

ENH add helper to store metadata in parquet files

---

doc/tutorials/add_solver.rst

Some code corrections in #635.

FIX - Code snippets in ``add_solver`` tutorial

---

benchopt/benchmark.py
benchopt/plotting/generate_html.py

Merge `standalone` into `allow_meta_from_json` for benchmarks.
Follow up on #231

Merge allow_meta_from_json and standalone

---

benchopt/cli/main.py
benchopt/utils/conda_env_cmd.py
benchopt/utils/misc.py
continuous_integration/test_req_detection.sh

FIX failing requirements

---

benchopt/tests/dummy_benchmark/solvers/python_pgd_callback.py

FIX: wrong indentation

---

README.rst

Small change so no documentation and unit tests were added.

Add a badge for latest doc

---

.circleci/config.yml
benchopt/config.py
benchopt/tests/test_config.py
setup.cfg

FIX config set for yaml files

---

README.rst
doc/available_benchmarks.rst

Syntax changed in https://github.com/badges/shields/issues/8671 ; badges were displaying incorrect values

FIX update benchmarks test badges

---

setup.cfg

Pytest current version

---

benchopt/plotting/generate_html.py
benchopt/runner.py
benchopt/stopping_criterion.py
benchopt/tests/test_benchmark_features.py
benchopt/tests/test_objective_outputs.py
benchopt/tests/test_stopping_criterion.py
benchopt/tests/utils/capture_run_output.py

ENH allow for non-numerical values in objective

---

benchopt/benchmark.py
benchopt/tests/fixtures.py
benchopt/tests/test_cli.py
benchopt/tests/utils/capture_run_output.py
benchopt/utils/dependencies_mixin.py

FIX solver install only depending on global requirements

---

benchopt/base.py
benchopt/callback.py
benchopt/runner.py
benchopt/tests/test_benchmark_features.py
benchopt/tests/test_solvers.py

Cln improve get result error

---

benchopt/benchmark.py
benchopt/cli/main.py
benchopt/runner.py
benchopt/tests/test_cli.py
benchopt/utils/terminal_output.py
doc/benchmark_workflow/index.rst
doc/benchmark_workflow/manage_benchmark_results.rst
doc/index.rst
doc/names.inc
doc/whats_new.rst

CLI add collect command to gather existing results

---

benchopt/utils/dynamic_modules.py

This should fix the unpickling error from scikit-adaptation/skada-bench#60

FIX make benchmark_utils func picklable

---

benchopt/cli/main.py
benchopt/tests/test_run_config_files.py
benchopt/utils/parametrized_name_mixin.py

Fix for #715 
- Allow to use a dictionary in solver list in config file.
- Fix display issue with template_parameter when an argument is a dictionary.

Fix solver complex params

---

doc/user_guide/advanced.rst

Fixed visible  `.. code-block:` line in Benchopt documentation

FIX visible `.. code-block:` command

---

.circleci/config.yml
.github/workflows/test.yml

Fix for https://github.com/benchopt/benchopt.github.io/issues/2 before moving to a better solution
closes #724

Clean doc folder before publishing website

---

doc/benchmark_workflow/write_benchmark.rst
doc/faq.rst
doc/user_guide/ml_benchmark.rst

DOC reference ML template

---

benchopt/config.py
benchopt/tests/test_benchmark_features.py

The doc says that the default is `benchmark_dir / data` but right now default is `benchmark_dir`.
This PR fixes this to the former one and add some more tests.

FIX default data_home+more test cases

---

benchopt/plotting/html/static/result.js
benchopt/plotting/html/templates/result.mako.html

Follow up on #675 
cc @Melvin-klein

FIX rename boxplot_chart->boxplot in result.js

---

benchopt/tests/test_deprecation.py
benchopt/utils/conda_env_cmd.py

The proposed approach used to handle deprecation fails, this is a fix, which adds test for the deprecated behavior.

FIX channel specified with one colon instead of 2

---

benchopt/cli/tests/test_cli.py

FIX test updated to match outputs from mamba and conda

---

benchopt/plotting/plot_objective_curve.py

Fix missing colors on benchmark plots

---

benchopt/benchmark.py
benchopt/cli/main.py
benchopt/runner.py
benchopt/tests/test_runner.py
benchopt/tests/utils/capture_run_output.py
doc/whats_new.rst

ENH add --no-cache option to disable caching

---

README.rst
doc/names.inc
doc/tutorials/build_benchmark.rst
doc/user_guide/CLI_ref.rst
doc/whats_new.rst

Fix the broken link in the README

---

benchopt/cli/main.py
benchopt/cli/tests/test_cli.py
doc/whats_new.rst

Fix n repetitions
